---
title: "2_batches_descriptives"
author: "Johanna Mehler"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true               # Enable Table of Contents
    toc_float:              # Make the TOC floating
      collapsed: false      # Do not collapse TOC by default
      smooth_scroll: true   # Smooth scrolling to sections
    number_sections: true   # Numbered sections
    theme: readable         # Use a predefined theme for styling (optional)
    highlight: tango        # Syntax highlighting style (optional)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Libraries

```{r, include=FALSE}
library(tidyverse)
library(descr) 
library(ggplot2)
library(descr)


theme_set(theme_minimal())
```

## Read in Data

```{r}
# read in batches
batches <- read_csv("/Users/Jo/OneDrive/1_Hertie Studies/Thesis/Hertie-Thesis-Mehler/data/batches_2.csv")
```

# Pre-Processing

Create numeric Values (TRUE = 1, FALSE = 0) for all columns and remove the country column for now. Create dataframes for each category content, target etc.

```{r}
# Replace 'Answer.' with '' for all column names starting with 'Answer.'
names(batches) <- sub("^Answer\\.", "", names(batches))

# Convert boolean (logical) columns to numeric
data_numeric <- batches %>% 
  select(-ends_with("open"), -flag_comments, -Input.country, -Input.hate_definition, -Input.ResponseId) %>% 
  mutate(across(.cols = everything(), .fns = ~ as.numeric(. == TRUE)))

# take out answers that are flagged for revision
data_numeric_filtered <- data_numeric %>% filter(flag.flag == FALSE) %>% select(-flag.flag)
data_numeric_filtered %>% write_csv("/Users/Jo/OneDrive/1_Hertie Studies/Thesis/Hertie-Thesis-Mehler/data/data_numeric_filtered_2.csv")

# create subsets for each category
data_content <- data_numeric %>% select(starts_with("content")) # 15
names(data_content) <- sub("^content\\.", "", names(data_content))

data_other_features <- data_numeric %>% select(starts_with("other")) # 7
names(data_other_features) <- sub("^other\\.", "", names(data_other_features))

data_scope <- data_numeric %>% select(starts_with("scope")) # 2
names(data_scope) <- sub("^scope\\.", "", names(data_scope))

data_sender <- data_numeric %>% select(starts_with("sender")) # 5
names(data_sender) <- sub("^sender\\.", "", names(data_sender))

data_target <- data_numeric %>% select(starts_with("target")) # 18
names(data_target) <- sub("^target\\.", "", names(data_target))
```

# Explore Distributions

```{r}
# Count the number of 1s in each column of the dataframe
ones_count <- colSums(data_numeric_filtered == 1)

# Convert the counts to a dataframe for plotting
ones_count_df <- data.frame(variable = names(ones_count), count = ones_count) 

# Order the variables by count in descending order
ones_count_df$variable <- reorder(ones_count_df$variable, -ones_count_df$count)

# Create a bar plot with each column's number of 1s
ggplot(ones_count_df, aes(x = variable, y = count)) +
  geom_bar(stat = "identity", fill = "skyblue", color = "black") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + # Rotate x-axis labels for better readability
  labs(title = "Counts per Classification Item", x = "Item", y = "Count")

```
```{r}
# Overall patterns: Count the frequency of TRUE values for each Answer.* column
overall_patterns <- colSums(data_numeric_filtered, na.rm = TRUE) # Assuming the first column is `Input.country`
overall_patterns_sorted <- sort(overall_patterns, decreasing = TRUE)

# Display the most common properties/content
head(overall_patterns_sorted, 15)
```

## Content items

```{r}
# Count the number of 1s in each column of the dataframe
ones_count_content <- colSums(data_content == 1)

# Convert the counts to a dataframe for plotting
ones_count_content_df <- data.frame(variable = names(ones_count_content), count = ones_count_content) 

# Create a bar plot with each column's number of 1s
ggplot(ones_count_content_df, aes(x = reorder(variable, -count), y = count)) +
  geom_bar(stat = "identity", fill = "skyblue", color = "black") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + # Rotate x-axis labels for better readability
  labs(title = "Counts per Content Item", x = "Item", y = "Count")

```

## Sender items

```{r}
# Count the number of 1s in each column of the dataframe
ones_count_sender <- colSums(data_sender == 1)

# Convert the counts to a dataframe for plotting
ones_count_sender_df <- data.frame(variable = names(ones_count_sender), count = ones_count_sender) 

# Create a bar plot with each column's number of 1s
ggplot(ones_count_sender_df, aes(x = reorder(variable, -count), y = count)) +
  geom_bar(stat = "identity", fill = "skyblue", color = "black") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + # Rotate x-axis labels for better readability
  labs(title = "Counts per Sender Item", x = "Item", y = "Count")

```

## Target items

```{r}
# Count the number of 1s in each column of the dataframe
ones_count_target <- colSums(data_target == 1)

# Convert the counts to a dataframe for plotting
ones_count_target_df <- data.frame(variable = names(ones_count_target), count = ones_count_target) 

# Create a bar plot with each column's number of 1s
ggplot(ones_count_target_df, aes(x = reorder(variable, -count), y = count)) +
  geom_bar(stat = "identity", fill = "skyblue", color = "black") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + # Rotate x-axis labels for better readability
  labs(title = "Counts per Target Item", x = "Item", y = "Count")

```

## Other Features of Statement

```{r}
# Count the number of 1s in each column of the dataframe
ones_count_other <- colSums(data_other_features == 1)

# Convert the counts to a dataframe for plotting
ones_count_data_other <- data.frame(variable = names(ones_count_other), count = ones_count_other) 

# Create a bar plot with each column's number of 1s
ggplot(ones_count_data_other, aes(x = reorder(variable, -count), y = count)) +
  geom_bar(stat = "identity", fill = "skyblue", color = "black") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + # Rotate x-axis labels for better readability
  labs(title = "Number of 1s per Variable", x = "Variable", y = "Count")

```

## Scope

```{r}
# Count the number of 1s in each column of the dataframe
ones_count_scope <- colSums(data_scope == 1)

# Convert the counts to a dataframe for plotting
ones_count_scope <- data.frame(variable = names(ones_count_scope), count = ones_count_scope) 

# Create a bar plot with each column's number of 1s
ggplot(ones_count_scope, aes(x = reorder(variable, -count), y = count)) +
  geom_bar(stat = "identity", fill = "skyblue", color = "black") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + # Rotate x-axis labels for better readability
  labs(title = "Scope", x = "Item", y = "Count")

```

# Items per person

```{r}
item_counts <- data_numeric %>% 
  # Convert TRUE/FALSE to 1/0 and sum them for each row
  mutate(TotalTrues = rowSums(across(everything()))) %>%
  # Arrange the data from most to fewest TRUEs
  arrange(desc(TotalTrues)) 

freq(item_counts$TotalTrues)
```


