---
title: "Political Orientation Score Descriptives"
author: "Johanna Mehler"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true               # Enable Table of Contents
    toc_float:              # Make the TOC floating
      collapsed: false      # Do not collapse TOC by default
      smooth_scroll: true   # Smooth scrolling to sections
    number_sections: true   # Numbered sections
    theme: readable         # Use a predefined theme for styling (optional)
    highlight: tango        # Syntax highlighting style (optional)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Load data and packages

```{r}
library(tidyverse)
library(descr)
library(ggplot2)
library(here)

# read in combined final dataset
data <- read_csv(here("data/data_combined.csv"))

data_all <- read_csv(here("data/data_clean.csv"))

pol_score <- data %>% select(leftright_pred_score)
```

# Check frequencies and distributions

## Distribution of the "real" variable leftright in my samples 

Distribution of my sample (n = 1133), Distribution of full sample (n > 19,000)


```{r}
# Distribution of training sample (n = 400)
freq(data$leftright)

# Distribution of test sample (n > 19,000)
freq(data_all$leftright)
```

## Descriptives of the new leftright_pred_score

```{r}
# Pol_score
descr(pol_score)
```

The mean error when predicting the leftright orientation was around 2.

```{r}
# Density of leftright_pred_score
ggplot(pol_score, aes(x = leftright_pred_score)) +
  geom_density(fill = "skyblue", alpha = 0.6) + # Adjust alpha for transparency
  theme_minimal() +
  labs(title = "Density of Leftright Pred Score",
       x = "Leftright Pred Score",
       y = "Density") +
  theme(legend.title = element_blank()) # Hide the legend title
```

## Lowest average scores

```{r}
# Sort the dataset by Average_Grade_Level in ascending order to get the 15 lowest scores
lowest_scores <- data %>%
  arrange(leftright_pred_score) %>%
  slice(1:15)

# Print Definition and leftright value
for (i in 1:nrow(lowest_scores)) {
  cat("# Leftright Value:", lowest_scores$leftright[i], "\n",
      "Open Hate Definition:", lowest_scores$hate_definition[i], "\n\n")
}
```

## Highest average scores

```{r}
# Sort the dataset by Average_Grade_Level in descending order to get the 15 highest scores
highest_scores <- data %>%
  arrange(desc(leftright_pred_score)) %>%
  slice(1:15)

# Print the texts corresponding to the highest scores
for (i in 1:nrow(highest_scores)) {
  cat("# Leftright Value:", highest_scores$leftright[i], "\n",
      "Open Hate Definition:", highest_scores$hate_definition[i], "\n\n")
}
```

